from __future__ import annotations

from inspect import cleandoc
from pathlib import Path
from subprocess import CompletedProcess
from typing import TYPE_CHECKING

import pytest
from packaging.version import Version

from scrapy_lint import _stacks
from scrapy_lint._stacks import Stack, find_conflict, stack_data

from . import ExpectedIssue, File
from .helpers import check_project

if TYPE_CHECKING:
    from collections.abc import Sequence

VENDORED_STACK = "scrapy:2.13-20250721"
STACK = "scrapy:2.99-20990101"
STACK_REQUIREMENTS = cleandoc(
    """
    #
    # This file is autogenerated by pip-compile with Python 3.12
    #
    scrapy==2.13.3
        # via -r requirements.in
    twisted[http2]==24.11.0
        # via scrapy
    unpinned>=1.0
    """
)
SCRAPINGHUB_YML = cleandoc(
    f"""
    stack: {STACK}
    requirements:
      file: requirements.txt
    """
)
CONFLICT = "Because scrapy==2.13.3 depends on twisted>=21.7.0"
UV_ERROR = f"  × No solution found when resolving dependencies:\n  ╰─▶ {CONFLICT}\n"  # noqa: RUF001
DETAIL = f"No solution found when resolving dependencies: {CONFLICT}"


@pytest.fixture
def cached_stack(stack_cache: Path) -> Path:
    path = stack_cache / "stacks" / "2.99-20990101.txt"
    path.parent.mkdir(parents=True)
    path.write_text(STACK_REQUIREMENTS, encoding="utf-8")
    return path


@pytest.mark.usefixtures("cached_stack")
def test_stack_data() -> None:
    stack = stack_data(STACK)
    assert stack == Stack(
        requirements={
            "scrapy": Version("2.13.3"),
            "twisted": Version("24.11.0"),
        },
        python_version="3.12",
    )


@pytest.mark.usefixtures("cached_stack")
@pytest.mark.parametrize(
    "value",
    [
        "scrapy:2.99",  # not frozen
        "scrapy:2.99-20990101-suffix",
        "custom:2.99-20990101",
    ],
)
def test_unsupported_stack(value: str) -> None:
    assert stack_data(value) is None


def test_vendored_stack() -> None:
    stack = stack_data(VENDORED_STACK)
    assert stack is not None
    assert stack.python_version == "3.12"
    assert stack.requirements["scrapy"] == Version("2.13.3")


def test_offline() -> None:
    assert stack_data(STACK) is None


def test_download_is_cached(monkeypatch: pytest.MonkeyPatch) -> None:
    downloads = []

    def download(url: str) -> str:
        downloads.append(url)
        return STACK_REQUIREMENTS

    monkeypatch.setattr(_stacks, "_download", download)
    assert stack_data(STACK) == stack_data(STACK)
    assert downloads == [
        "https://raw.githubusercontent.com/scrapinghub/scrapinghub-stack-scrapy"
        "/2.99-20990101/requirements.txt"
    ]


def fake_uv(
    monkeypatch: pytest.MonkeyPatch,
    failing: Sequence[str],
) -> list[list[str]]:
    """Make uv fail for inputs that pin any package in *failing*."""
    inputs = []

    def run(command: list[str], **_kwargs) -> CompletedProcess:
        requirements = Path(command[-1]).read_text(encoding="utf-8").splitlines()
        inputs.append(requirements)
        if any(requirement in failing for requirement in requirements):
            return CompletedProcess(command, 1, stderr=UV_ERROR)
        return CompletedProcess(command, 0, stderr="")

    monkeypatch.setattr(_stacks, "which", lambda _: "uv")
    monkeypatch.setattr(_stacks, "run", run)
    return inputs


def test_find_conflict(monkeypatch: pytest.MonkeyPatch) -> None:
    stack = Stack({"scrapy": Version("2.13.3")}, "3.12")
    inputs = fake_uv(monkeypatch, ["twisted==18.9.0"])
    conflict = find_conflict(stack, {"twisted": Version("18.9.0")})
    assert conflict == DETAIL
    assert inputs == [["scrapy==2.13.3"], ["scrapy==2.13.3", "twisted==18.9.0"]]


def test_no_conflict(monkeypatch: pytest.MonkeyPatch) -> None:
    stack = Stack({"scrapy": Version("2.13.3")}, "3.12")
    fake_uv(monkeypatch, [])
    assert find_conflict(stack, {"twisted": Version("24.11.0")}) is None


def test_unusable_resolver(monkeypatch: pytest.MonkeyPatch) -> None:
    """A stack that does not resolve on its own means no usable resolver."""
    stack = Stack({"scrapy": Version("2.13.3")}, "3.12")
    fake_uv(monkeypatch, ["scrapy==2.13.3"])
    assert find_conflict(stack, {"twisted": Version("18.9.0")}) is None


def test_no_uv() -> None:
    stack = Stack({"scrapy": Version("2.13.3")}, "3.12")
    assert find_conflict(stack, {"twisted": Version("18.9.0")}) is None


@pytest.mark.usefixtures("cached_stack")
def test_issue(monkeypatch: pytest.MonkeyPatch) -> None:
    fake_uv(monkeypatch, ["twisted==18.9.0"])
    check_project(
        [
            File("", path="scrapy.cfg"),
            File(SCRAPINGHUB_YML, path="scrapinghub.yml"),
            File("scrapy==2.13.3\ntwisted==18.9.0\n", path="requirements.txt"),
        ],
        [
            ExpectedIssue(
                "SCP13 incomplete requirements freeze",
                path="requirements.txt",
            ),
            ExpectedIssue(
                "SCP24 missing stack requirements: aiohttp, awscli, boto, boto3,"
                " jinja2, monkeylearn, pillow, pyyaml, requests, scrapinghub,"
                " scrapinghub-entrypoint-scrapy, scrapy-deltafetch,"
                " scrapy-dotpersistence, scrapy-magicfields, scrapy-pagestorage,"
                " scrapy-querycleaner, scrapy-splitvariants,"
                " scrapy-zyte-smartproxy, spidermon, urllib3",
                path="requirements.txt",
            ),
            ExpectedIssue(
                f"SCP47 stack requirement conflict: {STACK}: {DETAIL}",
                path="requirements.txt",
            ),
        ],
    )
