# Generated by utils/update_addons.py.
from packaging.version import Version

from scrapy_lint.addons import Addon, VersionedSettings
from scrapy_lint.settings import UNKNOWN_SETTING_VALUE
from scrapy_lint.versions import UNKNOWN_UNSUPPORTED_VERSION

DUPLICATE_URL_DISCARDER_ADDON = Addon(
    package="duplicate-url-discarder",
    settings=VersionedSettings(
        history={
            UNKNOWN_UNSUPPORTED_VERSION: {
                "DUD_FALLBACK_REQUEST_FINGERPRINTER_CLASS": UNKNOWN_SETTING_VALUE,
                "REQUEST_FINGERPRINTER_CLASS": "duplicate_url_discarder.Fingerprinter",
            },
            Version("0.2.0"): {
                "DUD_FALLBACK_REQUEST_FINGERPRINTER_CLASS": UNKNOWN_SETTING_VALUE,
                "ITEM_PIPELINES": {
                    "duplicate_url_discarder.DuplicateUrlDiscarderPipeline": 100,
                },
                "REQUEST_FINGERPRINTER_CLASS": "duplicate_url_discarder.Fingerprinter",
            },
        },
    ),
)


SCRAPY_POET_ADDON = Addon(
    package="scrapy-poet",
    settings=VersionedSettings(
        history={
            UNKNOWN_UNSUPPORTED_VERSION: {
                "DOWNLOADER_MIDDLEWARES": {
                    "scrapy_poet.InjectionMiddleware": 543,
                    "scrapy.downloadermiddlewares.stats.DownloaderStats": None,
                    "scrapy_poet.DownloaderStatsMiddleware": 850,
                },
                "REQUEST_FINGERPRINTER_CLASS": "scrapy_poet.ScrapyPoetRequestFingerprinter",
                "SPIDER_MIDDLEWARES": {
                    "scrapy_poet.RetryMiddleware": 275,
                },
            },
        },
    ),
)


SCRAPY_ZYTE_API_ADDON = Addon(
    package="scrapy-zyte-api",
    settings=VersionedSettings(
        history={
            UNKNOWN_UNSUPPORTED_VERSION: {
                "DOWNLOADER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPIDownloaderMiddleware": 1000,
                },
                "DOWNLOAD_HANDLERS": {
                    "http": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPDownloadHandler",
                    "https": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPSDownloadHandler",
                },
                "REQUEST_FINGERPRINTER_CLASS": "scrapy_zyte_api.ScrapyZyteAPIRequestFingerprinter",
                "SPIDER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPISpiderMiddleware": 100,
                },
                "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
                "ZYTE_API_FALLBACK_HTTPS_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_FALLBACK_HTTP_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_TRANSPARENT_MODE": True,
            },
            Version("0.19.0"): {
                "DOWNLOADER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPIDownloaderMiddleware": 633,
                    "scrapy_zyte_api.ScrapyZyteAPISessionDownloaderMiddleware": 667,
                },
                "DOWNLOAD_HANDLERS": {
                    "http": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPDownloadHandler",
                    "https": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPSDownloadHandler",
                },
                "REQUEST_FINGERPRINTER_CLASS": "scrapy_zyte_api.ScrapyZyteAPIRequestFingerprinter",
                "SPIDER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPISpiderMiddleware": 100,
                },
                "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
                "ZYTE_API_FALLBACK_HTTPS_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_FALLBACK_HTTP_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_TRANSPARENT_MODE": True,
            },
            Version("0.26.0"): {
                "DOWNLOADER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPIDownloaderMiddleware": 633,
                    "scrapy_zyte_api.ScrapyZyteAPISessionDownloaderMiddleware": 667,
                },
                "DOWNLOAD_HANDLERS": {
                    "http": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPDownloadHandler",
                    "https": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPSDownloadHandler",
                },
                "REQUEST_FINGERPRINTER_CLASS": "scrapy_zyte_api.ScrapyZyteAPIRequestFingerprinter",
                "SPIDER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPISpiderMiddleware": 100,
                    "scrapy_zyte_api.ScrapyZyteAPIRefererSpiderMiddleware": 1000,
                },
                "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
                "ZYTE_API_FALLBACK_HTTPS_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_FALLBACK_HTTP_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_TRANSPARENT_MODE": True,
            },
            Version("0.35.0"): {
                "DOWNLOADER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPISessionResetterDownloaderMiddleware": 565,
                    "scrapy_zyte_api.ScrapyZyteAPIDownloaderMiddleware": 633,
                    "scrapy_zyte_api.ScrapyZyteAPISessionDownloaderMiddleware": 667,
                },
                "DOWNLOAD_HANDLERS": {
                    "http": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPDownloadHandler",
                    "https": "scrapy_zyte_api.handler.ScrapyZyteAPIHTTPSDownloadHandler",
                },
                "REQUEST_FINGERPRINTER_CLASS": "scrapy_zyte_api.ScrapyZyteAPIRequestFingerprinter",
                "SPIDER_MIDDLEWARES": {
                    "scrapy_zyte_api.ScrapyZyteAPISpiderMiddleware": 100,
                    "scrapy_zyte_api.ScrapyZyteAPIRefererSpiderMiddleware": 1000,
                },
                "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
                "ZYTE_API_FALLBACK_HTTPS_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_FALLBACK_HTTP_HANDLER": UNKNOWN_SETTING_VALUE,
                "ZYTE_API_TRANSPARENT_MODE": True,
            },
        },
    ),
)


ZYTE_SPIDER_TEMPLATES_ADDON = Addon(
    package="zyte-spider-templates",
    settings=VersionedSettings(
        history={
            UNKNOWN_UNSUPPORTED_VERSION: {
                "CLOSESPIDER_TIMEOUT_NO_ITEM": 600,
                "DOWNLOADER_MIDDLEWARES": {
                    "zyte_spider_templates.MaxRequestsPerSeedDownloaderMiddleware": 100,
                    "scrapy.downloadermiddlewares.offsite.OffsiteMiddleware": None,
                    "zyte_spider_templates.AllowOffsiteMiddleware": 500,
                },
                "DUD_LOAD_RULE_PATHS": UNKNOWN_SETTING_VALUE,
                "ITEM_PROBABILITY_THRESHOLDS": {
                    "zyte_common_items.items.Article": 0.1,
                    "zyte_common_items.items.Product": 0.1,
                },
                "SCHEDULER_DISK_QUEUE": "scrapy.squeues.PickleFifoDiskQueue",
                "SCHEDULER_MEMORY_QUEUE": "scrapy.squeues.FifoMemoryQueue",
                "SCHEDULER_PRIORITY_QUEUE": "scrapy.pqueues.DownloaderAwarePriorityQueue",
                "SCRAPY_POET_DISCOVER": [
                    "zyte_spider_templates.pages",
                ],
                "SPIDER_MIDDLEWARES": {
                    "zyte_spider_templates.IncrementalCrawlMiddleware": 45,
                    "zyte_spider_templates.OffsiteRequestsPerSeedMiddleware": 49,
                    "zyte_spider_templates.TrackSeedsSpiderMiddleware": 550,
                    "zyte_spider_templates.OnlyFeedsMiddleware": 108,
                    "zyte_spider_templates.TrackNavigationDepthSpiderMiddleware": 110,
                    "zyte_spider_templates.CrawlingLogsMiddleware": 1000,
                },
                "SPIDER_MODULES": [
                    "zyte_spider_templates.spiders",
                ],
            },
            Version("0.11.1"): {
                "CLOSESPIDER_TIMEOUT_NO_ITEM": 600,
                "DOWNLOADER_MIDDLEWARES": {
                    "zyte_spider_templates.MaxRequestsPerSeedDownloaderMiddleware": 100,
                    "scrapy.downloadermiddlewares.offsite.OffsiteMiddleware": None,
                    "zyte_spider_templates.AllowOffsiteMiddleware": 50,
                },
                "DUD_LOAD_RULE_PATHS": UNKNOWN_SETTING_VALUE,
                "ITEM_PROBABILITY_THRESHOLDS": {
                    "zyte_common_items.items.Article": 0.1,
                    "zyte_common_items.items.Product": 0.1,
                },
                "SCHEDULER_DISK_QUEUE": "scrapy.squeues.PickleFifoDiskQueue",
                "SCHEDULER_MEMORY_QUEUE": "scrapy.squeues.FifoMemoryQueue",
                "SCHEDULER_PRIORITY_QUEUE": "scrapy.pqueues.DownloaderAwarePriorityQueue",
                "SCRAPY_POET_DISCOVER": [
                    "zyte_spider_templates.pages",
                ],
                "SPIDER_MIDDLEWARES": {
                    "zyte_spider_templates.IncrementalCrawlMiddleware": 45,
                    "zyte_spider_templates.OffsiteRequestsPerSeedMiddleware": 49,
                    "zyte_spider_templates.TrackSeedsSpiderMiddleware": 550,
                    "zyte_spider_templates.OnlyFeedsMiddleware": 108,
                    "zyte_spider_templates.TrackNavigationDepthSpiderMiddleware": 110,
                    "zyte_spider_templates.CrawlingLogsMiddleware": 1000,
                },
                "SPIDER_MODULES": [
                    "zyte_spider_templates.spiders",
                ],
            },
        },
    ),
)


ADDONS = {
    "duplicate_url_discarder.Addon": DUPLICATE_URL_DISCARDER_ADDON,
    "scrapy_poet.Addon": SCRAPY_POET_ADDON,
    "scrapy_zyte_api.Addon": SCRAPY_ZYTE_API_ADDON,
    "scrapy_zyte_api.addon.Addon": SCRAPY_ZYTE_API_ADDON,
    "zyte_spider_templates.Addon": ZYTE_SPIDER_TEMPLATES_ADDON,
}
