# /// script
# requires-python = ">=3.10"
# dependencies = ["packaging"]
# ///
from __future__ import annotations

import re
from json import loads
from pathlib import Path
from urllib.request import urlopen

from packaging.version import InvalidVersion, Version

BRANCHES_URL = (
    "https://api.github.com/repos/scrapinghub/scrapinghub-stack-scrapy"
    "/branches?per_page=100"
)
DOCKERFILE_URL = (
    "https://raw.githubusercontent.com/scrapinghub/scrapinghub-stack-scrapy"
    "/branch-{stack}/Dockerfile"
)
EOL_URL = "https://endoflife.date/api/python.json"
FROM_PYTHON = re.compile(r"^FROM python:(\d+(?:\.\d+)?)", re.MULTILINE)
OUTPUT_PATH = Path(__file__).parents[1] / "scrapy_lint" / "data" / "python.py"
TIMEOUT = 30


def main() -> None:
    """Vendor Python end-of-life dates and the Python version of every stack."""
    eol_dates = sorted_eol()
    eol = "\n".join(f'    "{k}": date({v}),' for k, v in eol_dates.items())
    stacks = "\n".join(
        f'    "{k}": "{v}",' for k, v in sorted_stacks(eol_dates).items()
    )
    OUTPUT_PATH.write_text(
        f"# Generated by utils/update_python.py.\n"
        f"from datetime import date\n\n"
        f"PYTHON_EOL = {{\n{eol}\n}}\n\n"
        f"STACK_PYTHON = {{\n{stacks}\n}}\n",
        encoding="utf-8",
    )
    print(f"Updated {OUTPUT_PATH.relative_to(Path.cwd())}")


def sorted_eol() -> dict[str, str]:
    """Return the end-of-life date of every Python version, as ``date`` args."""
    result = {}
    for entry in loads(download(EOL_URL)):
        eol = entry["eol"]
        if not isinstance(eol, str):
            continue
        year, month, day = eol.split("-")
        result[entry["cycle"]] = f"{int(year)}, {int(month)}, {int(day)}"
    return {k: result[k] for k in sorted(result, key=Version)}


def sorted_stacks(eol_dates: dict[str, str]) -> dict[str, str]:
    """Return the Python version of every Scrapy Cloud stack.

    Stacks that only name the major version of Python, e.g. ``python:2``, get
    the highest version of that major series in *eol_dates*.
    """
    result = {}
    for branch in loads(download(BRANCHES_URL)):
        stack = branch["name"].removeprefix("branch-")
        if stack == branch["name"]:
            continue
        match = FROM_PYTHON.search(download(DOCKERFILE_URL.format(stack=stack)))
        if not match:
            continue
        python = match[1]
        if "." not in python:
            series = [v for v in eol_dates if v.startswith(f"{python}.")]
            if not series:
                continue
            python = max(series, key=Version)
        result[stack] = python
    return {k: result[k] for k in sorted(result, key=stack_key)}


def stack_key(stack: str) -> tuple[Version, str]:
    number, _, suffix = stack.partition("-")
    try:
        return Version(number), suffix
    except InvalidVersion:
        return Version("0"), stack


def download(url: str) -> str:
    with urlopen(url, timeout=TIMEOUT) as response:  # noqa: S310
        return response.read().decode("utf-8")


if __name__ == "__main__":
    main()
